sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    after_success:
    r_packages:
    - devtools
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: false
install:
  - Rscript install_ackages.R
script:
  - Rscript generate_parameter_reports.R
branches:
  only:
  - master
