sudo: required
language: r
cran: https://cran.rstudio.com/
cache: packages
matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntugis/ubuntugis-unstable
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
        - libnetcdf-dev
        - netcdf-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - chmod 755 ./.push_results.sh
    after_success:
    r_packages:
    - devtools
    - ./.push_results.sh
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: false
install:
- Rscript install_packages.R
script:
- Rscript generate_parameter_reports.R
branches:
  only:
  - master
env:
  global:
    secure: mQkIKuB0UPBivcmudjiJf4RWmtFQ3Hx22cts64QSHY1BW0cvWQUzbhy2ON2t4uEYf00fvZIRC6lrJHQmzsYUt8onT65J24ZGIFN3jtt6wGUso10cIZMBftC2+ALAFEDnlMkFJEf+v85iNC1dwVf/jX9cz3hmSp7ENXBoeCqHUirJH5iGCv6bwIuWFQxGIA+e6/1ec/QVQVTqpizzTidHNf9rOQSwR9WsaxtXaNQ2iwSKaKPzGxSM6/Md4wha/PnCwSiPL5CLbsjGoWdNCPeGK7bKcu4/CzqaJmLM/aRDNypwxrsBRgjwiswNLmhpAAWj0nooFrsuPYAt2uSHLUHFqo7Qylwc9lbQc1tGUgWqe2vUmS9I7DICZOz3lwlXbNWD/xvTFwKOZOr4m+urJPxf99pmZsWfrDxRPNFjzDDPoqW6nW2m0GoAeAv7v/jT1LB9k+DpgKwZHIQC0ehj8uuDl9spE7c0kLLAnZXMnX0lYZQ7E7Y3vpF3hjh9/7CqArJEL1nw1minCABNzgmTyroMObuxCq9C9aoADayRdWAEVqVDhFqQHD/SF93+6rj5out5nDMCHTmkOW4tRF1GTC023eKvahWDoQTIdbJaMK75xeFrrCYvN7RQRGxvc/6vs84YwsQc5P4LjUYCvJ2ySCjdzr7JM2CPG6rygZUu4CyGDLo=
