sudo: required
language: r
cran: https://cran.rstudio.com/
cache: packages
matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntugis/ubuntugis-unstable
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
        - libnetcdf-dev
        - netcdf-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    after_success:
    r_packages:
    - devtools
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: false
install:
- Rscript install_packages.R
script:
- Rscript generate_parameter_reports.R
- Rscript push_back.R
branches:
  only:
  - master
env:
  global:
  - secure: 1P2z6Bb8z9EM0zfOT6sInxhWnLJsXWXmM95VMrXb5DbqPKDkpZchGcNh+r4dcl+kknQFcB8DYkKWgixcxbwCuoJuGXEBMW+5EIpYOJlRMA4IDH+0WwJmaFwQKk5ip98JVbrjYaWbez4Z8IJZeZcxhNJdHiD4FkR+CK2B5Wi1lkjtr1IlYWOA0dZW5qKBp2CZ2AFJQn+NrY8h14xLs0W8+fyxC8Z7oiO0gv5oUxLrDjGbWhF6gW+l0Mh2R/B44HevxDEGRj/WRps5xzS8dOwdttee8CBBhIVXIDNM9twK/ErpwGs71jb7DjiUKZaiY0bMaaivMIRKr0dg7p/pVxBG+SdqreASWx+8WK7R1VYTvSATdWtPo6PqocsdPlhb/hP95hdznM3oQLxC6xTTp8x2YpY1TDZMxPyUF8T4ZH/0q3MZpJprhlmOSLJjno5wGYcZFpvi+9+EVJapECeCWk+Be3nNwjDhIexEhE0elcIlkXM2KnoiBBImG0z4afHYlCkz5jhe0adn8uZe9vU33T2gVrzRyYrGOfKuk3TSQr2T110GkfX9ULSk4P3L2oU7JJ6EeX66ry2wOsOicjknDs/DI2D72+8VPMrhkm/AAi+WNwxJ0Tmyx8tZUjoyNmuAuvM3jdWG19LL8RUnH4hWAuVAWrPaYrYLfzfSRJaSOiH41D8=
