sudo: required
language: r
cran: https://cran.rstudio.com/
cache: packages
matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntugis/ubuntugis-unstable
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
        - libnetcdf-dev
        - netcdf-bin
        - libcgal-dev
        - libglu1-mesa-dev
        - libglu1-mesa-dev
        - libx11-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - chmod +x ./.push_results.sh
    after_success:
    r_packages:
    - devtools
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: false
install:
- Rscript install_packages.R
script:
- Rscript generate_parameter_reports.R
- Rscript push_back.R
env:
  global:
    secure: EfUpneOfzA0vsGdqmyWfc0NAyfIUjHH+vMUWhbTwuslaggdhW9UI1hmQuGxhVCGu4+oaEnq/FndKjJqbOTEtvOhckgeCQG6gdrPhx6y3KYODrgU0Uf2ODHmd7gbkvzdcbMYlORKlwSwN5OdgK7MIly3VJ9DzJzVBbuu0YMyjVNKZrqtn01UOkhMf1HupxiKJmJvl5NiOOAXASVDVQleGpfeZrklqKoiYsM6ejhFZQbSDU/BZnEqCbU6ZnfnEZvLWAwo43w9XKY0Mdtl7hFXHKhGnY8SZSlJP03za8r+dc8rGml6tHVZhGG25zsSlVnLcvIajXsqtcRsNDVv9AXKT/AgZGqorHwbhfmWCWrizkDYz8zbS5JcT23oj7NuL+uqg69TULcAZXiEZNodU0pOfOvobxoQkeiAJtQvv4KrpxcfbPl3LKbG1mBaQEVc/3TJUR7xgopjwmqAgdCssMhjnsRTgDp4XaroQCqJDfm8CouuvMvecsv8htRuOfRHlW6GVJkrjSZKa/EWbIS3oQw7ysAaUTGl1b1w9dVIueQCSJ5gjdviKysuAF8CgJTbSZ6E8lIspksL31LhFQpuWD5iwmXRuXJOfHojKx/65bWgRlSA0iFhzmsD9SPoZ7Cdfr1rjF8jsKMX5GB9LUVY2h4NWqndfcUT0iNPvheBuflEBg3I=
