sudo: required
language: r
cran: https://cran.rstudio.com/
cache: packages
matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntugis/ubuntugis-unstable
        packages:
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
        - gdal-bin
        - libnetcdf-dev
        - netcdf-bin
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - chmod 755 ./.push_results.sh
    after_success: 
    r_packages:
    - devtools
    - "./.push_results.sh"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: false
install:
- Rscript install_packages.R
script:
- Rscript generate_parameter_reports.R
branches:
  only:
  - master
env:
  global:
  - secure: mQkIKuB0UPBivcmudjiJf4RWmtFQ3Hx22cts64QSHY1BW0cvWQUzbhy2ON2t4uEYf00fvZIRC6lrJHQmzsYUt8onT65J24ZGIFN3jtt6wGUso10cIZMBftC2+ALAFEDnlMkFJEf+v85iNC1dwVf/jX9cz3hmSp7ENXBoeCqHUirJH5iGCv6bwIuWFQxGIA+e6/1ec/QVQVTqpizzTidHNf9rOQSwR9WsaxtXaNQ2iwSKaKPzGxSM6/Md4wha/PnCwSiPL5CLbsjGoWdNCPeGK7bKcu4/CzqaJmLM/aRDNypwxrsBRgjwiswNLmhpAAWj0nooFrsuPYAt2uSHLUHFqo7Qylwc9lbQc1tGUgWqe2vUmS9I7DICZOz3lwlXbNWD/xvTFwKOZOr4m+urJPxf99pmZsWfrDxRPNFjzDDPoqW6nW2m0GoAeAv7v/jT1LB9k+DpgKwZHIQC0ehj8uuDl9spE7c0kLLAnZXMnX0lYZQ7E7Y3vpF3hjh9/7CqArJEL1nw1minCABNzgmTyroMObuxCq9C9aoADayRdWAEVqVDhFqQHD/SF93+6rj5out5nDMCHTmkOW4tRF1GTC023eKvahWDoQTIdbJaMK75xeFrrCYvN7RQRGxvc/6vs84YwsQc5P4LjUYCvJ2ySCjdzr7JM2CPG6rygZUu4CyGDLo=
  - secure: tGpVFMDgZAqNymhvRhZivcb0m5aCh1DGFPj41mJECgpttpSzJK+SZ0u9q8K6fXhpU1vIP+7M7IClz9mMB6YqfeyC1JtIVQhZky1jlExHyuyDhd+G54wnB4/ukRx/OQcHgFigoTOJAVNg+AdHukAYMFk978TpZ7k0ImEaqwAEhI76r8Iyp5IEzQqgbcgtkQgjT6XTtGnoJ+jrEN8jZDo5cQO6fd0IY0iXKk5GJqo/Pa20fHJ7C1dNGbAwk10AEsjxJQoq4MZOXGQDxrbE5be39cNaoS4G41yalQ+KKIqJGfKctcbqLb7xI6CDL1PDSbBC+1loWXXFVOKSQbQjQJBpGRnkQx4yDmlo2WN+kFytv9aQL8cv6h0ih7eGlglkYRRFoY4SuKgXIViR1WnMwlV2F7zVQ5H3CjHGasPd8QVL86uIbshS53mG06mlEuYzjmDzXtXf8ttf0dewGItB07pxslTnD9Iz1yFVjnMFQkdfbqxlsQ+iX7YdkKFlb5yXA1MeYtyuhGghw7BgdFgwnnJLYkgmkrDFJYFmHIBcx5u67ia8yLsK+f5t4cFyDhYjVO1WHyHmAr/UAOVeQInZKOnNywr+xiVAuRb6qwW4ZhE7wbt6oeHm5+NDvDRgedJE0fPqdaqJRPokmJ/QJxFsXzVyJYQMjSqS+XPD4dx47uk9SC0=
